version: 2

project_name: gofafo

before:
  hooks:
    - go mod tidy

builds:
  - id: gofafo
    main: ./main.go
    binary: gofafo
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
      - README.md

checksum:
  name_template: "checksums.txt"

# Using legacy dockers (works today; prints a deprecation warning)
dockers:
  - id: image
    use: buildx
    dockerfile: Dockerfile
    image_templates:
      - ghcr.io/michalbiesek/gofafo:{{ .Tag }}
      - ghcr.io/michalbiesek/gofafo:latest
    build_flag_templates:
      - --platform=linux/amd64,linux/arm64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .Commit }}
      - --label=org.opencontainers.image.source={{ .GitURL }}
      - --label=org.opencontainers.image.created={{ .Date }}

release:
  github:
    owner: michalbiesek
    name: gofafo
  draft: false
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
      - "^test:"
