version: 2
project_name: gofafo

before:
  hooks:
    - go mod tidy

builds:
  - id: gofafo
    main: ./main.go
    binary: gofafo
    env:
      - CGO_ENABLED=0
    goos: [linux]    # Docker images only target Linux
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
      - README.md

checksum:
  name_template: "checksums.txt"

dockers_v2:
  - images:
      - ghcr.io/michalbiesek/gofafo
    tags:
      - "{{ .Tag }}"
      - "latest"
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      org.opencontainers.image.title: "{{ .ProjectName }}"
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.revision: "{{ .Commit }}"
      org.opencontainers.image.source: "{{ .GitURL }}"
      org.opencontainers.image.created: "{{ .Date }}"

release:
  github:
    owner: michalbiesek
    name: gofafo
  draft: false
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude: ["^docs:", "^chore:", "^test:"]
