version: 2

project_name: gofafo

before:
  hooks:
    - go mod tidy

builds:
  - id: gofafo
    main: ./main.go
    binary: gofafo
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
      - README.md

checksum:
  name_template: "checksums.txt"

# Build per-arch images, then stitch them with a manifest
dockers:
  - id: img_amd64
    use: buildx
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - ghcr.io/michalbiesek/gofafo:{{ .Tag }}-amd64
      - ghcr.io/michalbiesek/gofafo:latest-amd64
    build_flag_templates:
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .Commit }}
      - --label=org.opencontainers.image.source={{ .GitURL }}
      - --label=org.opencontainers.image.created={{ .Date }}

  - id: img_arm64
    use: buildx
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    image_templates:
      - ghcr.io/michalbiesek/gofafo:{{ .Tag }}-arm64
      - ghcr.io/michalbiesek/gofafo:latest-arm64
    build_flag_templates:
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .Commit }}
      - --label=org.opencontainers.image.source={{ .GitURL }}
      - --label=org.opencontainers.image.created={{ .Date }}

docker_manifests:
  - name_template: ghcr.io/michalbiesek/gofafo:{{ .Tag }}
    image_templates:
      - ghcr.io/michalbiesek/gofafo:{{ .Tag }}-amd64
      - ghcr.io/michalbiesek/gofafo:{{ .Tag }}-arm64
  - name_template: ghcr.io/michalbiesek/gofafo:latest
    image_templates:
      - ghcr.io/michalbiesek/gofafo:latest-amd64
      - ghcr.io/michalbiesek/gofafo:latest-arm64

release:
  github:
    owner: michalbiesek
    name: gofafo
  draft: false
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
      - "^test:"
